/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/balance/': RouteRecordInfo<
      '/balance/',
      '/balance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bought/': RouteRecordInfo<
      '/bought/',
      '/bought',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/chats/': RouteRecordInfo<
      '/chats/',
      '/chats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/creative/[id]': RouteRecordInfo<
      '/creative/[id]',
      '/creative/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/creative/edit/[id]': RouteRecordInfo<
      '/creative/edit/[id]',
      '/creative/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/creative/new/': RouteRecordInfo<
      '/creative/new/',
      '/creative/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/designers/': RouteRecordInfo<
      '/designers/',
      '/designers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/executing-projects/': RouteRecordInfo<
      '/executing-projects/',
      '/executing-projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/favorite/': RouteRecordInfo<
      '/favorite/',
      '/favorite',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/made-creatives/': RouteRecordInfo<
      '/made-creatives/',
      '/made-creatives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/made-projects/': RouteRecordInfo<
      '/made-projects/',
      '/made-projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moderation/': RouteRecordInfo<
      '/moderation/',
      '/moderation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moderation/creatives/': RouteRecordInfo<
      '/moderation/creatives/',
      '/moderation/creatives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moderation/users/': RouteRecordInfo<
      '/moderation/users/',
      '/moderation/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/orders/': RouteRecordInfo<
      '/orders/',
      '/orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/': RouteRecordInfo<
      '/profile/',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/[id]': RouteRecordInfo<
      '/project/[id]',
      '/project/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/project/edit/[id]': RouteRecordInfo<
      '/project/edit/[id]',
      '/project/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/project/new/': RouteRecordInfo<
      '/project/new/',
      '/project/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/registration/': RouteRecordInfo<
      '/registration/',
      '/registration',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/shop/': RouteRecordInfo<
      '/shop/',
      '/shop',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/shopping-cart/': RouteRecordInfo<
      '/shopping-cart/',
      '/shopping-cart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/shopping-cart/edit/[id]': RouteRecordInfo<
      '/shopping-cart/edit/[id]',
      '/shopping-cart/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/users/[id]': RouteRecordInfo<
      '/users/[id]',
      '/users/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/balance/index.vue': {
      routes:
        | '/balance/'
      views:
        | never
    }
    'src/pages/bought/index.vue': {
      routes:
        | '/bought/'
      views:
        | never
    }
    'src/pages/chats/index.vue': {
      routes:
        | '/chats/'
      views:
        | never
    }
    'src/pages/creative/[id].vue': {
      routes:
        | '/creative/[id]'
      views:
        | never
    }
    'src/pages/creative/edit/[id].vue': {
      routes:
        | '/creative/edit/[id]'
      views:
        | never
    }
    'src/pages/creative/new/index.vue': {
      routes:
        | '/creative/new/'
      views:
        | never
    }
    'src/pages/designers/index.vue': {
      routes:
        | '/designers/'
      views:
        | never
    }
    'src/pages/executing-projects/index.vue': {
      routes:
        | '/executing-projects/'
      views:
        | never
    }
    'src/pages/favorite/index.vue': {
      routes:
        | '/favorite/'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/pages/made-creatives/index.vue': {
      routes:
        | '/made-creatives/'
      views:
        | never
    }
    'src/pages/made-projects/index.vue': {
      routes:
        | '/made-projects/'
      views:
        | never
    }
    'src/pages/moderation/index.vue': {
      routes:
        | '/moderation/'
      views:
        | never
    }
    'src/pages/moderation/creatives/index.vue': {
      routes:
        | '/moderation/creatives/'
      views:
        | never
    }
    'src/pages/moderation/users/index.vue': {
      routes:
        | '/moderation/users/'
      views:
        | never
    }
    'src/pages/orders/index.vue': {
      routes:
        | '/orders/'
      views:
        | never
    }
    'src/pages/profile/index.vue': {
      routes:
        | '/profile/'
      views:
        | never
    }
    'src/pages/project/[id].vue': {
      routes:
        | '/project/[id]'
      views:
        | never
    }
    'src/pages/project/edit/[id].vue': {
      routes:
        | '/project/edit/[id]'
      views:
        | never
    }
    'src/pages/project/new/index.vue': {
      routes:
        | '/project/new/'
      views:
        | never
    }
    'src/pages/registration/index.vue': {
      routes:
        | '/registration/'
      views:
        | never
    }
    'src/pages/shop/index.vue': {
      routes:
        | '/shop/'
      views:
        | never
    }
    'src/pages/shopping-cart/index.vue': {
      routes:
        | '/shopping-cart/'
      views:
        | never
    }
    'src/pages/shopping-cart/edit/[id].vue': {
      routes:
        | '/shopping-cart/edit/[id]'
      views:
        | never
    }
    'src/pages/users/[id].vue': {
      routes:
        | '/users/[id]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
