/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/balance/': RouteRecordInfo<
      '/balance/',
      '/balance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bought/': RouteRecordInfo<
      '/bought/',
      '/bought',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/chats/': RouteRecordInfo<
      '/chats/',
      '/chats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/creative/edit/': RouteRecordInfo<
      '/creative/edit/',
      '/creative/edit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/creative/id/': RouteRecordInfo<
      '/creative/id/',
      '/creative/id',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/creative/new/': RouteRecordInfo<
      '/creative/new/',
      '/creative/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/designers/': RouteRecordInfo<
      '/designers/',
      '/designers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/editShoppingCart/': RouteRecordInfo<
      '/editShoppingCart/',
      '/editShoppingCart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/executingProjects/': RouteRecordInfo<
      '/executingProjects/',
      '/executingProjects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/favorite/': RouteRecordInfo<
      '/favorite/',
      '/favorite',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/madeCreatives/': RouteRecordInfo<
      '/madeCreatives/',
      '/madeCreatives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/madeProjects/': RouteRecordInfo<
      '/madeProjects/',
      '/madeProjects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/main/': RouteRecordInfo<
      '/main/',
      '/main',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moderation/': RouteRecordInfo<
      '/moderation/',
      '/moderation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moderation/creatives/': RouteRecordInfo<
      '/moderation/creatives/',
      '/moderation/creatives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moderation/users/': RouteRecordInfo<
      '/moderation/users/',
      '/moderation/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/orders/': RouteRecordInfo<
      '/orders/',
      '/orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/': RouteRecordInfo<
      '/profile/',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/edit/': RouteRecordInfo<
      '/project/edit/',
      '/project/edit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/id/': RouteRecordInfo<
      '/project/id/',
      '/project/id',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/new/': RouteRecordInfo<
      '/project/new/',
      '/project/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/registration/': RouteRecordInfo<
      '/registration/',
      '/registration',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/shop/': RouteRecordInfo<
      '/shop/',
      '/shop',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/shoppingCart/': RouteRecordInfo<
      '/shoppingCart/',
      '/shoppingCart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/': RouteRecordInfo<
      '/user/',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/balance/index.vue': {
      routes:
        | '/balance/'
      views:
        | never
    }
    'src/pages/bought/index.vue': {
      routes:
        | '/bought/'
      views:
        | never
    }
    'src/pages/chats/index.vue': {
      routes:
        | '/chats/'
      views:
        | never
    }
    'src/pages/creative/edit/index.vue': {
      routes:
        | '/creative/edit/'
      views:
        | never
    }
    'src/pages/creative/id/index.vue': {
      routes:
        | '/creative/id/'
      views:
        | never
    }
    'src/pages/creative/new/index.vue': {
      routes:
        | '/creative/new/'
      views:
        | never
    }
    'src/pages/designers/index.vue': {
      routes:
        | '/designers/'
      views:
        | never
    }
    'src/pages/editShoppingCart/index.vue': {
      routes:
        | '/editShoppingCart/'
      views:
        | never
    }
    'src/pages/executingProjects/index.vue': {
      routes:
        | '/executingProjects/'
      views:
        | never
    }
    'src/pages/favorite/index.vue': {
      routes:
        | '/favorite/'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/pages/madeCreatives/index.vue': {
      routes:
        | '/madeCreatives/'
      views:
        | never
    }
    'src/pages/madeProjects/index.vue': {
      routes:
        | '/madeProjects/'
      views:
        | never
    }
    'src/pages/main/index.vue': {
      routes:
        | '/main/'
      views:
        | never
    }
    'src/pages/moderation/index.vue': {
      routes:
        | '/moderation/'
      views:
        | never
    }
    'src/pages/moderation/creatives/index.vue': {
      routes:
        | '/moderation/creatives/'
      views:
        | never
    }
    'src/pages/moderation/users/index.vue': {
      routes:
        | '/moderation/users/'
      views:
        | never
    }
    'src/pages/orders/index.vue': {
      routes:
        | '/orders/'
      views:
        | never
    }
    'src/pages/profile/index.vue': {
      routes:
        | '/profile/'
      views:
        | never
    }
    'src/pages/project/edit/index.vue': {
      routes:
        | '/project/edit/'
      views:
        | never
    }
    'src/pages/project/id/index.vue': {
      routes:
        | '/project/id/'
      views:
        | never
    }
    'src/pages/project/new/index.vue': {
      routes:
        | '/project/new/'
      views:
        | never
    }
    'src/pages/registration/index.vue': {
      routes:
        | '/registration/'
      views:
        | never
    }
    'src/pages/shop/index.vue': {
      routes:
        | '/shop/'
      views:
        | never
    }
    'src/pages/shoppingCart/index.vue': {
      routes:
        | '/shoppingCart/'
      views:
        | never
    }
    'src/pages/user/index.vue': {
      routes:
        | '/user/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
